server: hub-cloud.browserstack.com
user: <user>
key: <key>

common_caps:
  build: capybara-browserstack
  browserstack.debug: true

browser_caps:
- browser: chrome
- browser: firefox
- browser: internet explorer
- browser: safari
